import type { Product, StockLedgerEntry, Invoice, StockTransfer, User, Role } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    sku: "PRD-001",
    name: "Wireless Mouse",
    category: "Electronics",
    unit: "pcs",
    salePrice: 29.99,
    costPrice: 15.0,
    stock: 150,
    reorderLevel: 50,
    status: "ACTIVE",
    createdAt: "2024-01-15",
    updatedAt: "2024-03-10",
  },
  {
    id: "2",
    sku: "PRD-002",
    name: "Mechanical Keyboard",
    category: "Electronics",
    unit: "pcs",
    salePrice: 89.99,
    costPrice: 45.0,
    stock: 75,
    reorderLevel: 25,
    status: "ACTIVE",
    createdAt: "2024-01-20",
    updatedAt: "2024-03-12",
  },
  {
    id: "3",
    sku: "PRD-003",
    name: "USB-C Cable",
    category: "Accessories",
    unit: "pcs",
    salePrice: 12.99,
    costPrice: 5.0,
    stock: 300,
    reorderLevel: 100,
    status: "ACTIVE",
    createdAt: "2024-02-01",
    updatedAt: "2024-03-15",
  },
  {
    id: "4",
    sku: "PRD-004",
    name: "Laptop Stand",
    category: "Accessories",
    unit: "pcs",
    salePrice: 49.99,
    costPrice: 25.0,
    stock: 45,
    reorderLevel: 20,
    status: "ACTIVE",
    createdAt: "2024-02-10",
    updatedAt: "2024-03-18",
  },
  {
    id: "5",
    sku: "PRD-005",
    name: "Webcam HD",
    category: "Electronics",
    unit: "pcs",
    salePrice: 79.99,
    costPrice: 40.0,
    stock: 15,
    reorderLevel: 30,
    status: "ACTIVE",
    createdAt: "2024-02-15",
    updatedAt: "2024-03-20",
  },
]

export const mockStockLedger: Record<string, StockLedgerEntry[]> = {
  "1": [
    {
      id: "1",
      productId: "1",
      createdAt: "2024-03-20",
      type: "sale",
      quantity: -10,
      balance: 150,
      reference: "INV-1001",
      note: "Customer order",
    },
    {
      id: "2",
      productId: "1",
      createdAt: "2024-03-18",
      type: "purchase",
      quantity: 50,
      balance: 160,
      reference: "PO-2001",
      note: "Restocking",
    },
    {
      id: "3",
      productId: "1",
      createdAt: "2024-03-15",
      type: "sale",
      quantity: -15,
      balance: 110,
      reference: "INV-1000",
      note: "Bulk order",
    },
    {
      id: "4",
      productId: "1",
      createdAt: "2024-03-10",
      type: "adjustment",
      quantity: 5,
      balance: 125,
      reference: "ADJ-001",
      note: "Inventory correction",
    },
  ],
}

export const mockInvoices: Invoice[] = [
  {
    id: "1",
    invoiceNumber: "INV-1001",
    customerName: "Acme Corporation",
    date: "2024-03-20",
    dueDate: "2024-04-20",
    status: "paid",
    subtotal: 299.9,
    tax: 29.99,
    total: 329.89,
    items: [
      {
        id: "1",
        productId: "1",
        productName: "Wireless Mouse",
        quantity: 10,
        price: 29.99,
        total: 299.9,
      },
    ],
  },
  {
    id: "2",
    invoiceNumber: "INV-1002",
    customerName: "Tech Solutions Inc",
    date: "2024-03-18",
    dueDate: "2024-04-18",
    status: "pending",
    subtotal: 179.98,
    tax: 18.0,
    total: 197.98,
    items: [
      {
        id: "1",
        productId: "2",
        productName: "Mechanical Keyboard",
        quantity: 2,
        price: 89.99,
        total: 179.98,
      },
    ],
  },
  {
    id: "3",
    invoiceNumber: "INV-1003",
    customerName: "Global Enterprises",
    date: "2024-03-15",
    dueDate: "2024-04-15",
    status: "overdue",
    subtotal: 649.92,
    tax: 65.0,
    total: 714.92,
    items: [
      {
        id: "1",
        productId: "3",
        productName: "USB-C Cable",
        quantity: 50,
        price: 12.99,
        total: 649.5,
      },
    ],
  },
  {
    id: "4",
    invoiceNumber: "INV-1004",
    customerName: "StartUp Labs",
    date: "2024-03-22",
    dueDate: "2024-04-22",
    status: "draft",
    subtotal: 149.97,
    tax: 15.0,
    total: 164.97,
    items: [
      {
        id: "1",
        productId: "4",
        productName: "Laptop Stand",
        quantity: 3,
        price: 49.99,
        total: 149.97,
      },
    ],
  },
]

export const mockStockTransfers: StockTransfer[] = [
  {
    id: "1",
    transferNumber: "TRF-001",
    fromLocation: "Warehouse A",
    toLocation: "Warehouse B",
    date: "2024-03-20",
    status: "completed",
    items: [
      {
        id: "1",
        productId: "1",
        productName: "Wireless Mouse",
        quantity: 25,
      },
    ],
    notes: "Regular stock rebalancing",
  },
  {
    id: "2",
    transferNumber: "TRF-002",
    fromLocation: "Warehouse B",
    toLocation: "Retail Store",
    date: "2024-03-18",
    status: "in-transit",
    items: [
      {
        id: "1",
        productId: "2",
        productName: "Mechanical Keyboard",
        quantity: 10,
      },
      {
        id: "2",
        productId: "3",
        productName: "USB-C Cable",
        quantity: 50,
      },
    ],
    notes: "Store restocking",
  },
  {
    id: "3",
    transferNumber: "TRF-003",
    fromLocation: "Warehouse A",
    toLocation: "Warehouse C",
    date: "2024-03-22",
    status: "pending",
    items: [
      {
        id: "1",
        productId: "4",
        productName: "Laptop Stand",
        quantity: 15,
      },
    ],
  },
  {
    id: "4",
    transferNumber: "TRF-004",
    fromLocation: "Warehouse C",
    toLocation: "Warehouse A",
    date: "2024-03-15",
    status: "draft",
    items: [
      {
        id: "1",
        productId: "5",
        productName: "Webcam HD",
        quantity: 5,
      },
    ],
    notes: "Draft transfer",
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@company.com",
    role: "admin",
    status: "active",
    createdAt: "2024-01-15",
    lastLogin: "2024-03-22",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@company.com",
    role: "manager",
    status: "active",
    createdAt: "2024-02-01",
    lastLogin: "2024-03-21",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike.johnson@company.com",
    role: "observer",
    status: "active",
    createdAt: "2024-02-15",
    lastLogin: "2024-03-20",
  },
  {
    id: "4",
    name: "Sarah Williams",
    email: "sarah.williams@company.com",
    role: "observer",
    status: "inactive",
    createdAt: "2024-03-01",
    lastLogin: "2024-03-10",
  },
]

export const mockRoles: Role[] = [
  {
    id: "1",
    name: "Administrator",
    description: "Full system access with all permissions",
    permissions: [
      "products.create",
      "products.edit",
      "products.delete",
      "sales.create",
      "sales.edit",
      "sales.delete",
      "inventory.manage",
      "reports.view",
      "settings.manage",
      "users.manage",
    ],
    userCount: 1,
  },
  {
    id: "2",
    name: "Manager",
    description: "Can manage products, sales, and view reports",
    permissions: ["products.create", "products.edit", "sales.create", "sales.edit", "inventory.manage", "reports.view"],
    userCount: 1,
  },
  {
    id: "3",
    name: "Observer",
    description: "View-only access to the system",
    permissions: ["products.view", "sales.create", "sales.view", "inventory.view"],
    userCount: 2,
  },
]
